### ISSUE TITLE
pls help

### ISSUE THREAD

**Issue by noxjho** [michielst/twitch-clips-compilation-bot#3]
Traceback (most recent call last):
  File "bot.py", line 18, in <module>
    parameters = Parameters(script_name=sys.argv[0], destination=sys.argv[1],
IndexError: list index out of range

**Comment by noxjho** [comment]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/peewee.py", line 3057, in execute_sql
    cursor.execute(sql, params or ())
